sources:
  - name: OpenMeteo
    handler:
      openapi:
        source: https://raw.githubusercontent.com/open-meteo/open-meteo/main/openapi.yml
        endpoint: https://api.open-meteo.com
        ignoreErrorResponses: true

  - name: JSONPlaceholder
    handler:
      openapi:
        source: ./jsonplaceholder-openapi.yaml
        endpoint: https://jsonplaceholder.typicode.com
        ignoreErrorResponses: true

serve:
  hostname: 0.0.0.0
  port: 4000
